3 architecture
alextsk/conway-game-of-life pull request #6
Opened 2018-09-16 18:12 UTC by alextsk

fixes #3 
fixes #2 - изменения с правилами были уже в #5, они должны были остаться в stash но что-то пошло не так

2018-09-18 04:31 UTC, chmnkh requested changes

2018-09-18 04:31 UTC, chmnkh commented on src/Model/Model.ts
> +class Model extends Observer{
Не смотря на код внутри класса Observer: модель обзервером быть не может. Все что она должна делать - это что-то тихо внутри себя вычислять и пулять уведомления во внешний мир типа "я вычислила вот это", ни за кем "наблюдать" и знать о ком-то модель не может.
На той же риззоме есть ссылки на нормальные статьи на тему MVC и примеры реализации обзервера там, можешь как за основу взять. Сейчас у тебя по архитектуре с обзервером странно реализовано :)

2018-09-18 04:31 UTC, chmnkh commented on src/Model/Model.ts
> +  state: any;
это где-то нужно?
тут же: any - зло, от которого почти всегда можно избавиться

2018-09-18 04:31 UTC, chmnkh commented on src/Model/Model.ts
> +    this.addObserver(Messages.TOGGLE, (data) => {
В дополнение к замечанию про обзервер выше: не может какой-то объект сам себе наблюдателей назначить, потому что тогда получается, что он о них что-то знает, а не должен. Ему вообще должно быть все равно, кто там за ним наблюдает и что за этим последует.

2018-09-18 04:31 UTC, chmnkh commented on src/Model/Logic/Logic.ts
> +  private gameUpdate(state: Grid): Grid {
не используется

2018-09-18 04:31 UTC, chmnkh commented on src/Model/Logic/Logic.ts
> +  toggleCell(grid: Grid, x: number, y: number): Grid {
модификатор доступа не прописан

2018-09-18 04:31 UTC, chmnkh commented on src/Model/Logic/Logic.ts
>      return +state[y - 1][x - 1];
тут явно тернарник напрашивается)

2018-09-18 04:31 UTC, chmnkh commented on src/Model/Logic/Logic.ts
>      return this.getCellState(grid, x, y) ? this.killCell(grid, x, y) : this.reviveCell(grid, x, y);
Здесь лучше было бы добавить лишнюю строчку кода на переменную с результатом проверки того, жива ли клетка или мертва, а не кастовать результат getCellState в булин. Тогда ты не будешь завязан на то, вернет ли он у тебя 0 или 1, плюс читаться намного лучше будет, чем сейчас.

А вообще: по хорошему, если у тебя метод toggleCell называется, то он просто (как и любой toggle-что-то) должен менять состояние клетки на противоположное. Было 1 стало 0, было 0 стало 1. Никакая еще логика там быть не должна. Вероятнее всего, тут ты где-то избыточной логики написал. Либо внутри метода, либо снаружи, и тогда он не нужен, а можно использовать какие-то другие методы.

2018-09-18 04:31 UTC, chmnkh commented on src/Model/Logic/Logic.ts
>      return +state[y - 1][x - 1];
Состояния клетки (0 или 1) не надо литералами писать, у тебя же енум есть.
В updateState (почему кстати state, а не grid (в именах параметров тоже то grid то state)?) тоже кучу литералов поубирать можно, в константы там вынести что-то (всякие индекс + 1 штуки можно оставить, разумеется).

2018-09-18 04:31 UTC, chmnkh commented on src/Model/State/State.ts
>      this.isStable = false;
Несколько замечаний:

- generateField - если ты начал называть сущность grid, то пусть она везде будет grid, а не где-то grid, а где-то field, если ты еще допишешь generateRandom..., то будет еще круче и более явно то, что делает метод;
- isStable - название тоже неудачное, вообще не понятно, о чем речь;
- поскольку generateField используется только в рамках resetGrid, то у меня вообще возникают подозрения, что вот это вот 

```
    this.isStable = false;
    this.prevGrids = [];
```
должно быть не в нем, а в resetGrid;

- зачем принимать грид параметром? твой рандомный грид же никак от старого не зависит, и вот это вот
```
this.setGrid(this.generateField(this.createGrid(this.width, this.height)));
```
красивее намного станет. Если задача метода "сгенерировать рандомный грид текущих размеров", то так и создавай его внутри исходя из текущих размеров.

2018-09-18 04:31 UTC, chmnkh commented on src/Model/State/State.ts
>      return <any[]>(new Array(y)).fill('').map(() => (new Array(x)).fill(CellState.Dead));// tslint:disable-line
не надо any использовать)
лучше пустую строку тоже на какой-нибудь null заменить, строка тут коряво выглядит и не к месту

2018-09-18 04:31 UTC, chmnkh commented on src/Model/State/State.ts
> +  private setGrid(newGrid, changeHistory: boolean = false) {
Метод setGrid у тебя пытается на двух стульях сразу усидеть: из-за наличия влага changeHistory он у тебя в разных контекстах использоваться может и разные задачи выполнять, хотя метод должен делать что-то одно всегда. По сути, именно "setGrid" выполняет только строчка this.grid = deepClone(newGrid), всё. Комбинация этой штуки с обновлением prevGrid - это уже другая задача. 
По идее, запись нового грида в this.grid своего метода не требует, а вот уже запись + обновление предыдущих гридов (т.е. работа метода с флагом) - имеет смысл вынести в свой метод. Но тогда там флага никакого не будет уже, и метод будет называться как-то по-другому, по смыслу того что он делает и где используется.

2018-09-18 04:31 UTC, chmnkh commented on src/Model/State/State.ts
> +    this.setGrid(this.logic.updateState(this.getGrid()), true);
тут то можно уже не публичный геттер использовать, а напрямую свойство)

2018-09-18 07:59 UTC, alextsk commented on src/Model/Model.ts
> +    this.addObserver(Messages.TOGGLE, (data) => {
сейчас так и есть, ему все равно. он тут не назначает себе наблюдателей, он просто слушает сообщение TOGGLE, все равно от кого. я могу его в чистом поле вызвать и он будет слушать свои события и слать сообщения

2018-09-18 07:59 UTC, alextsk commented on src/Model/Model.ts
> +class Model extends Observer{
модель сейчас ни о ком не знает. и про нее никто не знает. сама модель ни на кого явно не подписывается, только реагирует на сообщения и шлет другие сообщения, она event emitter, так же как и view.

2018-09-18 08:06 UTC, alextsk commented on src/Model/Model.ts
> +class Model extends Observer{
модель сейчас это event emitter, она так и делает - тихо вычисляет и пуляет. кто за ней смотрит она не в курсе, и она точно ни за  кем не смотрит.
вот эта схема у меня реализована, в статье из ризомы она тоже есть
![image](https://user-images.githubusercontent.com/16453186/45673169-32e02f00-bb54-11e8-8ef4-ba15d48f26ae.png)

2018-09-18 10:54 UTC, alextsk commented on src/Model/State/State.ts
> +    this.setGrid(this.logic.updateState(this.getGrid()), true);
геттер оставить или свойство публичным сделать?

2018-09-18 10:54 UTC, alextsk commented on src/Model/State/State.ts
> +  private setGrid(newGrid, changeHistory: boolean = false) {
сделал

2018-09-18 10:54 UTC, alextsk commented on src/Model/State/State.ts
>      return <any[]>(new Array(y)).fill('').map(() => (new Array(x)).fill(CellState.Dead));// tslint:disable-line
сделал

2018-09-18 10:55 UTC, alextsk commented on src/Model/State/State.ts
>      this.isStable = false;
done

2018-09-18 10:55 UTC, alextsk commented on src/Model/Logic/Logic.ts
>      return this.getCellState(grid, x, y) ? this.killCell(grid, x, y) : this.reviveCell(grid, x, y);
done

2018-09-18 10:56 UTC, alextsk commented on src/Model/Logic/Logic.ts
>      return +state[y - 1][x - 1];
сделал

2018-09-18 10:57 UTC, alextsk commented on src/Model/Logic/Logic.ts
> +  toggleCell(grid: Grid, x: number, y: number): Grid {
ок

2018-09-18 10:57 UTC, alextsk commented on src/Model/Logic/Logic.ts
> +  private gameUpdate(state: Grid): Grid {
убрал

2018-09-18 10:57 UTC, alextsk commented on src/Model/Model.ts
> +  state: any;
убрал

2018-09-21 09:15 UTC, chmnkh commented
Добавь в коллаборейтеры этого репо, чтобы мержить можно было, и вмержи этот пр, а то все исправления в нем делать уже неудобно становится.

2018-09-21 09:20 UTC, chmnkh approved these changes

2018-09-21 09:20 UTC, merged